steps:
# 1. Fetch the blog code and content
- name: gcr.io/cloud-builders/git
  args: ['clone', 'https://github.com/marcacohen/mcohen.io.git']
# 2. Run hugo command to generate static site
- name: docker.io/marcacohen/hugo-image
#- run: cd public && sw-precache --static-file-globs='**/!(*404*)'
#- run: firebase deploy --token=${FIREBASE_TOKEN}
