languageCode = "en-us"
title = "Marc Cohen"
baseurl = "http://mcohen.io/"

[params]
  title = "Marc Cohen"
  description = 'Technology, music, books, and more.'
  logo = "fa-code"
  copyright = "2017, Marc A. Cohen"

[[params.social]]
  medium = "twitter"
  icon = "twitter"
  link = "#"

[[params.social]]
  medium = "facebook"
  icon = "facebook"
  link = "#"

[[params.social]]
  medium = "instagram"
  icon = "instagram"
  link = "#"

[[params.social]]
  medium = "github"
  icon = "github"
  link = "#"
