languageCode = "en-us"
defaultContentLanguage = "en-us"
title = "Marc Cohen"
baseurl = "https://www.mcohen.io/"
disqusShortname = "https-www-mcohen-io"

[params]
  title = "Marc Cohen"
  logo = "fa-code"
  site_author = "Marc Cohen"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"
