BaseURL = "https://www.mcohen.io/"
languageCode = "en-us"
title = "Marc Cohen"
paginate = 10
googleAnalytics = "UA-90004457-1"
DisqusShortname = "https-www-mcohen-io"
PygmentsCodeFences = true
PygmentsStyle = "monokai"

[Params]
    twitter = "marcacohen"
    description = "Marc Cohen's Personal Blog"
    email = "mco@google.com"
    hostname = "mcohen.io"

[Permalinks]
    post = "/:year/:title/"
    addendum = "/addendum/:year/:title/"

[Author]
    name = "Marc Cohen"
    twitter = "marcacohen"
    email = "mco@google.com"

[Taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"

[Indexes]
    tag = "tags"
    topic = "topics"
