BaseURL = "https://www.mcohen.io/"
languageCode = "en-us"
title = "Marc Cohen"
paginate = 10
googleAnalytics = "UA-90004457-1"
DisqusShortname = "https-www-mcohen-io"
PygmentsCodeFences = true
PygmentsStyle = "vim"

[params]
    twitter = "marcacohen"
    description = "Marc Cohen's Personal Blog"
    email = "mco@google.com"
    hostname = "mcohen.io"

[permalinks]
    post = "/:year/:title/"
    addendum = "/addendum/:year/:title/"

[author]
    name = "Marc Cohen"
    twitter = "marcacohen"
    email = "mco@google.com"

[taxonomies]
    tag = "tags"
    category = "categories"
    series = "series"
