version: 2
jobs:
  build:
    working_directory: ~/build
    docker:
      - image: onepill/golang-python
    steps:
      - checkout
      - run: pip install Pygments
      - run: go get -u -v github.com/kardianos/govendor
      - run: go get -u -v github.com/spf13/hugo
      - run: cd $GOPATH/src/github.com/spf13/hugo && govendor sync && go install
      - run: npm install -g firebase-tools
      - run: cd $HOME/gopath/src/github.com/marcacohen/mcohen.io && hugo
      - run: firebase deploy --token=${FIREBASE_API_TOKEN}
