version: 2
jobs:
  build:
    working_directory: ~/build
    docker:
      - image: circleci/cci-demo-go-primary:0.0.2
    steps:
      - checkout
      - run: sudo pip install Pygments
      - run: go get -u -v github.com/kardianos/govendor
      - run: go get -u -v github.com/spf13/hugo
      - run: cd $GOPATH/src/github.com/spf13/hugo && govendor sync && go install
      - run: npm install -g firebase-tools
      - run: cd $HOME/gopath/src/github.com/marcacohen/mcohen.io && hugo
      - run: firebase deploy --token=${FIREBASE_API_TOKEN}
