version: 2
jobs:
  build:
    working_directory: ~/build
    docker:
      - image: marcacohen/hugo-image
    steps:
      - checkout
      - run: hugo
      - run: firebase deploy --token=${FIREBASE_TOKEN}
